controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

show_list:
    path:      '/show'
    controller: 'App\Controller\HomeController::showAllUser'
    methods:   [GET]
